import {CONFIG} from './config';
export {CONFIG} from './config';
export type Resource='hint'|'undo'|'shuffle';
export type Tile={key:number,x:number,y:number,z:number,pair:number,half:'a'|'b',hidden?:boolean};
export const manifest=Array.from({length:CONFIG.librarySize},(_,i)=>{const n=String(i+1).padStart(2,'0');return {id:i+1,a:`/images/pairs/pair-${n}-a.webp`,b:`/images/pairs/pair-${n}-b.webp`,reveal:`/images/pairs/pair-${n}-reveal.webp`}});
export function uncovered(t:Tile,board:Tile[]){return !board.some(b=>b.z>t.z&&Math.abs(b.x-t.x)<1&&Math.abs(b.y-t.y)<1)}
export function free(t:Tile,board:Tile[]){return uncovered(t,board)&&(!board.some(b=>b.z===t.z&&b.y===t.y&&b.x===t.x-1)||!board.some(b=>b.z===t.z&&b.y===t.y&&b.x===t.x+1))}
function random<T>(a:T[]){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
export function order(board:Tile[]){let left=[...board];const seq:Tile[]=[];while(left.length){const t=random(left.filter(t=>free(t,left)))[0];if(!t)throw Error('Invalid geometry');seq.push(t);left=left.filter(b=>b.key!==t.key)}return seq}
export function geometry(){const out:Tile[]=[];for(let z=0;z<3;z++){const w=z===2?2:4,h=z===0?6:2;for(let y=0;y<h;y++)for(let x=0;x<w;x++)out.push({key:out.length,x:x+(4-w)/2,y:y+(6-h)/2,z,pair:0,half:'a'})}return out}
export function deal(){const ids=random(manifest.slice(0,CONFIG.availablePairCount).map(p=>p.id)).slice(0,CONFIG.pairCount);return order(geometry()).map((t,i)=>({...t,pair:ids[Math.floor(i/2)],half:(i%2?'b':'a') as Tile['half']}))}
export function redistribute(board:Tile[],rack:Tile[]){const seq=order(board);const identities=board.map(t=>({pair:t.pair,half:t.half}));const assigned:typeof identities=[];for(const r of rack){const i=identities.findIndex(t=>t.pair===r.pair);if(i>=0)assigned.push(...identities.splice(i,1))}const ids=random([...new Set(identities.map(t=>t.pair))]);for(const id of ids)assigned.push(...random(identities.filter(t=>t.pair===id)));return seq.map((t,i)=>({...t,...assigned[i]}))}
export type Game={level:number,board:Tile[],rack:Tile[],completed:number,streak:number,bestStreak:number,elapsed:number,started:boolean,reveal:number|null,status:'playing'|'won',resources:Record<Resource,number>,highlight:number[],message:string};
export function levelDeal(level:number){const board=deal();const ratio=CONFIG.hiddenTileRatios[Math.min(level-1,CONFIG.hiddenTileRatios.length-1)];const candidates=random(board.filter(t=>!free(t,board)));const hidden=new Set(candidates.slice(0,Math.round(board.length*ratio)).map(t=>t.key));return board.map(t=>({...t,hidden:hidden.has(t.key)}))}
export function exposePlayable(board:Tile[]){return board.map(t=>t.hidden&&free(t,board)?{...t,hidden:false}:t)}
export function newGame(bonus:Partial<Record<Resource,number>>={},level=1):Game{return {level,board:levelDeal(level),rack:[],completed:0,streak:0,bestStreak:0,elapsed:0,started:false,reveal:null,status:'playing',resources:{hint:CONFIG.initialResources+(bonus.hint||0),undo:CONFIG.initialResources+(bonus.undo||0),shuffle:CONFIG.initialResources+(bonus.shuffle||0)},highlight:[],message:'Tap a gold-bordered tile to begin.'}}
export function select(g:Game,key:number):Game{const t=g.board.find(t=>t.key===key);if(!t||g.reveal||g.status!=='playing'||!free(t,g.board))return g;const match=g.rack.find(r=>r.pair===t.pair);if(g.rack.length>=CONFIG.rackCapacity&&!match)return {...g,message:'Rack full. Undo, or shuffle and select a matching half.'};const board=exposePlayable(g.board.filter(b=>b.key!==key));if(match){const streak=g.streak+1,reward=CONFIG.streakRewards[streak as keyof typeof CONFIG.streakRewards] as {hint?:number,shuffle?:number}|undefined;return {...g,board,rack:g.rack.filter(r=>r.key!==match.key),completed:g.completed+1,streak,bestStreak:Math.max(g.bestStreak,streak),resources:{...g.resources,hint:g.resources.hint+(reward?.hint||0),shuffle:g.resources.shuffle+(reward?.shuffle||0)},started:true,reveal:t.pair,highlight:[],message:reward?`Streak bonus: ${reward.hint?'+1 Hint':'+1 Shuffle'}`:'A perfect pair.'}}return {...g,board,rack:[...g.rack,t],started:true,streak:g.rack.length?0:g.streak,highlight:[],message:g.rack.length===3?'Rack full. Undo or shuffle to recover.':'Find its other half.'}}
export function use(g:Game,r:Resource):Game{if(g.resources[r]<=0||g.status!=='playing'||g.reveal)return g;if(r==='undo'){if(!g.rack.length)return {...g,message:'No unmatched tile to undo.'};return {...g,board:exposePlayable([...g.board,g.rack[g.rack.length-1]]),rack:g.rack.slice(0,-1),resources:{...g.resources,undo:g.resources.undo-1},highlight:[],message:'Last tile restored.'}}if(r==='shuffle')return {...g,board:exposePlayable(redistribute(g.board,g.rack)),resources:{...g.resources,shuffle:g.resources.shuffle-1},highlight:[],message:'Fresh arrangement. Rack halves have priority.'};const playable=g.board.filter(t=>free(t,g.board));const mate=playable.find(t=>g.rack.some(r=>r.pair===t.pair));const pair=playable.find(t=>playable.some(b=>b.key!==t.key&&b.pair===t.pair));const highlight=mate?[mate.key]:pair?playable.filter(t=>t.pair===pair.pair).map(t=>t.key):[];return highlight.length?{...g,highlight,resources:{...g.resources,hint:g.resources.hint-1},message:'Follow the gold glow.'}:{...g,message:'No free match. Try undo or shuffle.',highlight:[]}}
export function tick(g:Game,seconds=1):Game{if(!g.started||g.reveal||g.status!=='playing')return g;return {...g,elapsed:g.elapsed+Math.max(0,seconds)}}
export function completionReward(elapsed:number){return CONFIG.completionRewards.find(t=>elapsed<=t.maxSeconds)!}
export function continueGame(g:Game):Game{return {...g,reveal:null,status:g.completed===CONFIG.pairCount?'won':g.status}}
