'use client';
import {useEffect,useState,useRef} from 'react';
import {CONFIG,manifest,newGame,select,use,tick,completionReward,continueGame,free,uncovered,type Tile,type Resource} from './engine';
import './style.css';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import type {ReactNode} from 'react';
import {flushSync} from 'react-dom';
import {registerGameTools} from './webmcp';
import {TileButton} from './TileButton';
import {fitTable} from './layout-fit';
import {inspectionAfterPeek,inspectedFaceVisible,type PeekPositions} from './peek';
import {OfflineArtNotice} from './OfflineArtNotice';
// Replace this adapter with a rewarded-ad provider. Resolves only after a earned reward.
const rewardedAds={async show(onProgress:(n:number)=>void){for(let n=CONFIG.rewardVideoSeconds;n>0;n--){onProgress(n);await new Promise(r=>setTimeout(r,1000))}return true}};
const fmt=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const AGE_PREF='mah-age-ok';
export default function App({initialGame}:{initialGame:ReturnType<typeof newGame>}){const [g,setG]=useState(initialGame);const [video,setVideo]=useState<Resource|null>(null);const [count,setCount]=useState(3);const [help,setHelp]=useState(false);const [best,setBest]=useState(0);const [quiet,setQuiet]=useState(false);const [intro,setIntro]=useState(true);const [introLeaving,setIntroLeaving]=useState(false);const [ageGate,setAgeGate]=useState<'pending'|'needed'|'ok'|'left'>(()=>{if(typeof window==='undefined')return 'pending';try{return localStorage.getItem(AGE_PREF)==='true'?'ok':'needed'}catch{return 'needed'}});
const peeks=useRef<PeekPositions>({});
const [inspected,setInspected]=useState<number|null>(null);
function onInspect(key:number){const t=g.board.find(t=>t.key===key);setInspected(t?.hidden&&!free(t,g.board)?key:null)}
function onPeek(key:number,offset:{x:number,y:number}){const next={...peeks.current};if(!offset.x&&!offset.y)delete next[key];else next[key]=offset;peeks.current=next;if(offset.x||offset.y)setInspected(previous=>inspectionAfterPeek(g.board,next,previous))}
useEffect(()=>{const raw=Number(localStorage.getItem('mah-level')||1);const level=Number.isSafeInteger(raw)&&raw>0?raw:1;if(level!==initialGame.level)setG(newGame({},level))},[]);
useEffect(()=>{peeks.current={};setInspected(null);setBest(Number(localStorage.getItem(`mah-best-level-${g.level}`)||(g.level===1?localStorage.getItem('mah-best-time-v2'):0)||0))},[g.level]);
function startLevel(level:number,bonus:Partial<Record<Resource,number>>={}){peeks.current={};setInspected(null);setIntroLeaving(false);setIntro(true);localStorage.setItem('mah-level',String(level));setG(newGame(bonus,level))}
function enterLevel(){if(introLeaving)return;setIntroLeaving(true);window.setTimeout(()=>{setIntro(false);setIntroLeaving(false)},650)}
const viewport=useRef<HTMLElement>(null),tableStage=useRef<HTMLDivElement>(null);
useEffect(()=>{if(ageGate!=='ok')return;const stage=tableStage.current,root=viewport.current;if(!stage||!root)return;const resize=()=>{const {boardWidth,tileWidth}=fitTable(stage.clientWidth,stage.clientHeight);root.style.setProperty('--board-width',`${boardWidth}px`);root.style.setProperty('--tile-width',`${tileWidth}px`)};const observer=new ResizeObserver(resize);observer.observe(stage);resize();return()=>observer.disconnect()},[ageGate]);
const current=useRef({g,blocked:true});current.current={g,blocked:ageGate!=='ok'||!!video||help};
useEffect(()=>registerGameTools(()=>current.current,next=>flushSync(()=>setG(next))),[]);
useEffect(()=>{setQuiet(localStorage.getItem('mah-quiet')==='true')},[]);
useEffect(()=>{try{setAgeGate(localStorage.getItem(AGE_PREF)==='true'?'ok':'needed')}catch{setAgeGate('needed')}},[]);
useEffect(()=>{if(intro||!g.started||g.reveal||g.status!=='playing'||video||help)return;let last=performance.now();const id=setInterval(()=>{const now=performance.now();const delta=(now-last)/1000;last=now;setG(g=>tick(g,delta))},100);return()=>clearInterval(id)},[intro,g.started,g.reveal,g.status,video,help]);
useEffect(()=>{if(g.status==='won'&&(!best||g.elapsed<best)){setBest(g.elapsed);localStorage.setItem(`mah-best-level-${g.level}`,String(g.elapsed))}},[g.status,g.elapsed,best,g.level]);
function resource(r:Resource){if(r==='shuffle'||r==='undo')setInspected(null);if(g.resources[r])setG(g=>use(g,r));else{setCount(CONFIG.rewardVideoSeconds);setVideo(r);rewardedAds.show(setCount).then(earned=>{if(earned)setG(g=>({...g,resources:{...g.resources,[r]:g.resources[r]+1}}));setVideo(null)})}}
function tile(t:Tile,rack=false){return <TileButton key={`${g.level}-${t.key}`} tile={t} rack={rack} playable={!rack&&free(t,g.board)} inspectable={!rack&&uncovered(t,g.board)&&g.status==='playing'&&!g.reveal} hinted={g.highlight.includes(t.key)} visible={rack||inspectedFaceVisible(t,g.board,inspected)} onPeek={onPeek} onInspect={onInspect} onBlocked={()=>setG(g=>({...g,message:'That tile is not playable yet.'}))} onSelect={()=>setG(g=>select(g,t.key))}/>}
const danger=g.rack.length===CONFIG.rackCapacity;
if(ageGate!=='ok')return <AgeGate mode={ageGate==='left'?'left':ageGate==='pending'?'pending':'needed'} onEnter={()=>{try{localStorage.setItem(AGE_PREF,'true')}catch{}setAgeGate('ok')}} onLeave={()=>setAgeGate('left')} onBack={()=>setAgeGate('needed')}/>;
return <main ref={viewport} className={`game-screen ${quiet?'quiet':''}`}><header><span className="level-label">LEVEL {g.level}</span><button className="round" aria-label="How to play" onClick={()=>setHelp(true)}>?</button></header><section className="stats"><div><small>PAIRS</small><strong>{g.completed}<em> / {CONFIG.pairCount}</em></strong></div><div><small>STREAK</small><strong><i>✦</i> {g.streak}</strong></div></section><div ref={tableStage} className="board-stage"><section className="board" aria-label="Mahjong board"><div className="felt-mark">M</div>{g.board.map(t=>tile(t))}</section></div><section className={`rack-section ${danger?'danger':''}`}><div className="rack-heading"><h2>WORK AREA</h2><span>{g.rack.length} <em>/ {CONFIG.rackCapacity}</em></span></div><div className="rack">{Array.from({length:CONFIG.rackCapacity},(_,i)=><div className="slot" key={i}>{g.rack[i]?tile(g.rack[i],true):<span>◇</span>}</div>)}</div><p className="message" aria-live="polite">{g.message}</p></section><section className="tools" aria-label="Game tools">{(['shuffle','hint','undo'] as Resource[]).map((r,i)=><button key={r} className="tool-button" aria-label={`${r[0].toUpperCase()+r.slice(1)}, ${g.resources[r]} available${g.resources[r]?'':', watch a video to earn one'}`} onClick={()=>resource(r)} disabled={g.status!=='playing'}><span className="tool-icon" aria-hidden="true">{['⇄','✦','↶'][i]}</span><span className="tool-count">{g.resources[r]}</span><span className="tool-caption">{r[0].toUpperCase()+r.slice(1)}</span></button>)}</section><footer><span>BEST {best?fmt(best):'—'}</span><button onClick={()=>{const q=!quiet;setQuiet(q);localStorage.setItem('mah-quiet',String(q))}}>{quiet?'Motion off':'Motion on'}</button><button onClick={()=>{if(confirm('Restart this level?'))startLevel(g.level)}}>Retry ↗</button></footer>
{intro&&<div className={`level-intro ${introLeaving?'leaving':''}`} role="dialog" aria-modal="true" aria-label={`Level ${g.level} start`}><div className="intro-panel intro-left"/><div className="intro-panel intro-right"/><div className="intro-content"><span className="intro-eyebrow">LEVEL {g.level}</span><h2>Play with<br/><em>Mah Boobs</em></h2><button className="intro-continue" onClick={enterLevel} disabled={introLeaving}>Continue <span aria-hidden="true">→</span></button></div></div>}
{g.reveal&&<Modal title="Pair matched" reveal><small className="eyebrow">A PERFECT PAIR</small><h2>Beautifully matched.</h2><RevealContinue onContinue={()=>setG(continueGame)}/><div className="reveal-image"><img src={manifest[g.reveal-1].reveal} alt={`Complete artwork for pair ${g.reveal}`}/></div><div className="reveal-meta"><span>PAIR {String(g.reveal).padStart(2,'0')}</span><span>✦ STREAK {g.streak}</span></div><p>{g.message}</p><BannerAd/><small className="paused">Timer paused · take a moment</small></Modal>}
{video&&<Modal title="Game dialog"><small className="eyebrow">REWARDED VIDEO · DEMO</small><div className="video-symbol">▷</div><h2>A little second chance.</h2><p>Earn +1 {video}. Your timer is paused.</p><div className="ad-placeholder">SIMULATED ADVERTISEMENT</div><strong className="countdown">{count}</strong><small className="paused">Reward arrives when the countdown ends</small></Modal>}
{g.status==='won'&&!g.reveal&&<Modal title="Level complete"><small className="eyebrow">LEVEL {g.level} CLEARED</small><h2>A flawless finish.</h2><div className="stars">{'★'.repeat(completionReward(g.elapsed).stars)}</div><div className="result"><span>Completion time <b>{fmt(g.elapsed)}</b></span><span>Best time <b>{fmt(best?Math.min(best,g.elapsed):g.elapsed)}</b></span><span>Best streak <b>{g.bestStreak}</b></span></div><div className="speed-reward"><small className="eyebrow">SPEED REWARD</small><p>{completionReward(g.elapsed).stars===3?'+1 Hint and +1 Shuffle for your next level':completionReward(g.elapsed).stars===2?'+1 Hint for your next level':'Finish in 4 minutes to earn a bonus Hint. Finish in 2:30 to earn a bonus Shuffle too.'}</p></div><button className="primary" onClick={()=>startLevel(g.level+1,completionReward(g.elapsed).bonus)}>Next Level →</button></Modal>}
{help&&<Modal title="Game dialog"><small className="eyebrow">HOW TO PLAY</small><h2>Two halves. One match.</h2><p>Tap tiles with a gold border. A tile must have nothing above it and an open left or right edge.</p><p>Drag an uncovered tile in any direction to see underneath. Release to snap it back. Peeking does not collect a tile or unlock the tiles beneath it. You can also hold any arrow key on a focused top tile to peek.</p><p>Later levels mix face-up artwork with patterned tile backs. Face-down tiles turn up when they become playable; only your most recently inspected hidden tile stays face-up. Inspect another tile and the previous one flips back.</p><p>Collect matching A + B halves in the four-slot work area. Pairs clear automatically. A full rack is recoverable: Undo a tile or Shuffle, then tap a half matching your rack.</p><p>Keep matching without collecting extra unmatched halves to build a streak. Earn a Hint at 5 and a Shuffle at 8.</p><p>There is no time limit. Active play time is tracked privately and shown when you finish. Clear the table within 4 minutes for an extra Hint next level, or within 2:30 for an extra Hint and Shuffle.</p><button className="primary" onClick={()=>setHelp(false)}>Back to the table →</button></Modal>}
<OfflineArtNotice/>
</main>}
function BannerAd(){return <div className="ad-placeholder" aria-label="Reserved banner advertisement">ADVERTISEMENT</div>}

function RevealContinue({onContinue}:{onContinue:()=>void}){const [ready,setReady]=useState(false);useEffect(()=>{const id=window.setTimeout(()=>setReady(true),6000);return()=>window.clearTimeout(id)},[]);return <div className="reveal-action-row">{ready&&<button className="reveal-continue" onClick={onContinue}>Continue <span aria-hidden="true">→</span></button>}</div>}

function Modal({children,title,reveal=false}:{children:ReactNode,title:string,reveal?:boolean}){return <Dialog open><DialogContent showCloseButton={false} className={`modal ${reveal?"reveal":""}`}><DialogTitle className="sr-only">{title}</DialogTitle>{children}</DialogContent></Dialog>}

function AgeGate({mode,onEnter,onLeave,onBack}:{mode:'pending'|'needed'|'left',onEnter:()=>void,onLeave:()=>void,onBack:()=>void}){
 const enterRef=useRef<HTMLButtonElement>(null);
 const backRef=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(mode==='needed')enterRef.current?.focus();if(mode==='left')backRef.current?.focus()},[mode]);
 useEffect(()=>{if(mode!=='needed')return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onLeave()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[mode,onLeave]);
 const panels=<><div className="intro-panel intro-left" aria-hidden="true"/><div className="intro-panel intro-right" aria-hidden="true"/></>;
 if(mode==='pending')return <div className="age-gate" role="status" aria-busy="true"><p className="sr-only">Loading.</p>{panels}</div>;
 if(mode==='left')return <dialog className="age-gate" open aria-labelledby="age-gate-left-title" aria-describedby="age-gate-left-copy">{panels}<div className="age-gate-content"><span className="intro-eyebrow">THE MATCHING ROOM</span><h1 id="age-gate-left-title">That&apos;s all for now</h1><p id="age-gate-left-copy">This experience is for adults. You can close this page whenever you like.</p><button ref={backRef} className="age-gate-leave" type="button" onClick={onBack}>Go back</button></div></dialog>;
 return <dialog className="age-gate" open aria-labelledby="age-gate-title" aria-describedby="age-gate-copy">{panels}<div className="age-gate-content"><span className="intro-eyebrow">THE MATCHING ROOM</span><h1 id="age-gate-title">Adults only</h1><p id="age-gate-copy">This matching game includes nudity and sexual imagery. Confirm you are 18 or older, or of legal age where you live, before you enter.</p><div className="age-gate-actions"><button ref={enterRef} className="intro-continue" type="button" onClick={onEnter}>I am 18+ · Enter</button><button className="age-gate-leave" type="button" onClick={onLeave}>I&apos;m under 18 · Leave</button></div></div></dialog>;
}
