'use client';
import {useEffect,useState,useRef} from 'react';
import {CONFIG,manifest,newGame,select,use,tick,completionReward,continueGame,free,type Tile,type Resource} from './engine';
import './style.css';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import type {ReactNode} from 'react';
import {flushSync} from 'react-dom';
import {registerGameTools} from './webmcp';
// Replace this adapter with a rewarded-ad provider. Resolves only after a earned reward.
const rewardedAds={async show(onProgress:(n:number)=>void){for(let n=CONFIG.rewardVideoSeconds;n>0;n--){onProgress(n);await new Promise(r=>setTimeout(r,1000))}return true}};
const fmt=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export default function App({initialGame}:{initialGame:ReturnType<typeof newGame>}){const [g,setG]=useState(initialGame);const [video,setVideo]=useState<Resource|null>(null);const [count,setCount]=useState(3);const [help,setHelp]=useState(false);const [best,setBest]=useState(0);const [quiet,setQuiet]=useState(false);
const current=useRef({g,blocked:!!video||help});current.current={g,blocked:!!video||help};
useEffect(()=>registerGameTools(()=>current.current,next=>flushSync(()=>setG(next))),[]);
useEffect(()=>{setBest(Number(localStorage.getItem('mah-best-time-v2')||0));setQuiet(localStorage.getItem('mah-quiet')==='true')},[]);
useEffect(()=>{if(!g.started||g.reveal||g.status!=='playing'||video||help)return;let last=performance.now();const id=setInterval(()=>{const now=performance.now();const delta=(now-last)/1000;last=now;setG(g=>tick(g,delta))},100);return()=>clearInterval(id)},[g.started,g.reveal,g.status,video,help]);
useEffect(()=>{if(g.status==='won'&&(!best||g.elapsed<best)){setBest(g.elapsed);localStorage.setItem('mah-best-time-v2',String(g.elapsed))}},[g.status,g.elapsed,best]);
function resource(r:Resource){if(g.resources[r])setG(g=>use(g,r));else{setCount(CONFIG.rewardVideoSeconds);setVideo(r);rewardedAds.show(setCount).then(earned=>{if(earned)setG(g=>({...g,resources:{...g.resources,[r]:g.resources[r]+1}}));setVideo(null)})}}
function tile(t:Tile,rack=false){const playable=rack||free(t,g.board);return <button key={t.key} aria-label={`Pair ${t.pair} ${t.half==='a'?'left':'right'} half${playable?'':' blocked'}`} disabled={rack||!playable} className={`tile ${playable?'free':'blocked'} ${g.highlight.includes(t.key)?'hinted':''}`} style={rack?{}:{left:`${t.x*15.5+2+t.z*.7}%`,top:`${t.y*23+5-t.z*1.7}%`,zIndex:t.z*10+1}} onClick={()=>setG(g=>select(g,t.key))}><img draggable={false} src={manifest[t.pair-1][t.half]} alt=""/><span>{String(t.pair).padStart(2,'0')}<b>{t.half.toUpperCase()}</b></span></button>}
const danger=g.rack.length===CONFIG.rackCapacity;
return <main className={quiet?'quiet':''}><header><div className="brand"><span className="brand-mark">M</span><h1>Mah Boobs<span>THE MATCHING ROOM</span></h1></div><button className="round" aria-label="How to play" onClick={()=>setHelp(true)}>?</button></header><section className="stats"><div><small>PAIRS</small><strong>{g.completed}<em> / {CONFIG.pairCount}</em></strong></div><div><small>STREAK</small><strong><i>✦</i> {g.streak}</strong></div></section><div className="board-heading"><span>THE TABLE</span><span>DEAL OF 18 PAIRS</span></div><section className="board" aria-label="Mahjong board"><div className="felt-mark">M</div>{g.board.map(t=>tile(t))}{!g.started&&<span className="table-note">Match the left and right halves</span>}</section><section className={`rack-section ${danger?'danger':''}`}><div className="rack-heading"><h2>WORK AREA</h2><span>{g.rack.length} <em>/ {CONFIG.rackCapacity}</em></span></div><div className="rack">{Array.from({length:CONFIG.rackCapacity},(_,i)=><div className="slot" key={i}>{g.rack[i]?tile(g.rack[i],true):<span>◇</span>}</div>)}</div><p className="message" aria-live="polite">{g.message}</p></section><section className="tools">{(['hint','undo','shuffle'] as Resource[]).map((r,i)=><button key={r} onClick={()=>resource(r)} disabled={g.status!=='playing'}><span className="tool-icon">{['✧','↶','⇄'][i]}</span><span className="tool-name">{r[0].toUpperCase()+r.slice(1)} <b>×{g.resources[r]}</b></span>{!g.resources[r]&&<small>WATCH VIDEO +1</small>}</button>)}</section><footer><span>BEST {best?fmt(best):'—'}</span><button onClick={()=>{const q=!quiet;setQuiet(q);localStorage.setItem('mah-quiet',String(q))}}>{quiet?'Motion off':'Motion on'}</button><button onClick={()=>{if(confirm('Start a new game?'))setG(newGame())}}>New game ↗</button></footer>
{g.reveal&&<Modal title="Pair matched" reveal><small className="eyebrow">A PERFECT PAIR</small><h2>Beautifully matched.</h2><div className="reveal-image"><img src={manifest[g.reveal-1].reveal} alt={`Complete placeholder artwork for pair ${g.reveal}`}/></div><div className="reveal-meta"><span>PAIR {String(g.reveal).padStart(2,'0')}</span><span>✦ STREAK {g.streak}</span></div><p>{g.message}</p><BannerAd/><button className="primary" onClick={()=>setG(continueGame)}>Continue <span>→</span></button><small className="paused">Timer paused · take a moment</small></Modal>}
{video&&<Modal title="Game dialog"><small className="eyebrow">REWARDED VIDEO · DEMO</small><div className="video-symbol">▷</div><h2>A little second chance.</h2><p>Earn +1 {video}. Your timer is paused.</p><div className="ad-placeholder">SIMULATED ADVERTISEMENT</div><strong className="countdown">{count}</strong><small className="paused">Reward arrives when the countdown ends</small></Modal>}
{g.status==='won'&&!g.reveal&&<Modal title="Level complete"><small className="eyebrow">TABLE CLEARED</small><h2>A flawless finish.</h2><div className="stars">{'★'.repeat(completionReward(g.elapsed).stars)}</div><div className="result"><span>Completion time <b>{fmt(g.elapsed)}</b></span><span>Best time <b>{fmt(best?Math.min(best,g.elapsed):g.elapsed)}</b></span><span>Best streak <b>{g.bestStreak}</b></span></div><div className="speed-reward"><small className="eyebrow">SPEED REWARD</small><p>{completionReward(g.elapsed).stars===3?'+1 Hint and +1 Shuffle for your next game':completionReward(g.elapsed).stars===2?'+1 Hint for your next game':'Finish in 4 minutes to earn a bonus Hint. Finish in 2:30 to earn a bonus Shuffle too.'}</p></div><button className="primary" onClick={()=>setG(newGame(completionReward(g.elapsed).bonus))}>New Game →</button></Modal>}
{help&&<Modal title="Game dialog"><small className="eyebrow">HOW TO PLAY</small><h2>Two halves. One match.</h2><p>Tap tiles with a bright border. A tile must have nothing above it and an open left or right edge.</p><p>Collect matching A + B halves in the four-slot work area. Pairs clear automatically. A full rack is recoverable: Undo a tile or Shuffle, then tap a half matching your rack.</p><p>Keep matching without collecting extra unmatched halves to build a streak. Earn a Hint at 5 and a Shuffle at 8.</p><p>There is no time limit. Active play time is tracked privately and shown when you finish. Clear the table within 4 minutes for an extra Hint next game, or within 2:30 for an extra Hint and Shuffle.</p><button className="primary" onClick={()=>setHelp(false)}>Back to the table →</button></Modal>}
</main>}
function BannerAd(){return <div className="ad-placeholder" aria-label="Reserved banner advertisement">ADVERTISEMENT</div>}

function Modal({children,title,reveal=false}:{children:ReactNode,title:string,reveal?:boolean}){return <Dialog open><DialogContent showCloseButton={false} className={`modal ${reveal?"reveal":""}`}><DialogTitle className="sr-only">{title}</DialogTitle>{children}</DialogContent></Dialog>}
