'use client';
import {useRef,useState,useEffect} from 'react';
import type {PointerEvent,KeyboardEvent} from 'react';
import {manifest,type Tile} from './engine';
import {peekOffset} from './peek';
export function TileButton({tile:t,rack,playable,inspectable,hinted,visible,onPeek,onInspect,onBlocked,onSelect}:{tile:Tile,rack:boolean,playable:boolean,inspectable:boolean,hinted:boolean,visible:boolean,onPeek:(key:number,offset:{x:number,y:number})=>void,onInspect:(key:number)=>void,onBlocked:()=>void,onSelect:()=>void}){
 const button=useRef<HTMLButtonElement>(null);
 const [offset,setOffset]=useState({x:0,y:0});
 const gesture=useRef<{id:number,x:number,y:number,width:number,dragging:boolean}|null>(null);
 const tileWidth=useRef(1);
 const suppressClick=useRef(false);
 function shake(){const el=button.current;if(!el)return;if(typeof el.getAnimations==='function')el.getAnimations().forEach(animation=>animation.cancel());if(typeof el.animate==='function'){el.animate([{transform:'translateX(0)'},{transform:'translateX(-5px) rotate(-1deg)',offset:.18},{transform:'translateX(5px) rotate(1deg)',offset:.36},{transform:'translateX(-4px) rotate(-.7deg)',offset:.54},{transform:'translateX(4px) rotate(.7deg)',offset:.72},{transform:'translateX(-1px)',offset:.88},{transform:'translateX(0)'}],{duration:500,easing:'ease-out'})}else{el.classList.remove('blocked-shake');void el.offsetWidth;el.classList.add('blocked-shake');window.setTimeout(()=>el.classList.remove('blocked-shake'),520)}}
 function blockedFeedback(){shake();onBlocked()}
 function down(e:PointerEvent<HTMLButtonElement>){if(!e.isPrimary||e.button!==0)return;suppressClick.current=false;if(!inspectable){if(!playable){blockedFeedback();suppressClick.current=true}return}onInspect(t.key);tileWidth.current=e.currentTarget.offsetWidth;gesture.current={id:e.pointerId,x:e.clientX,y:e.clientY,width:e.currentTarget.offsetWidth,dragging:false};e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e:PointerEvent<HTMLButtonElement>){const start=gesture.current;if(!start||start.id!==e.pointerId)return;const peek=peekOffset(e.clientX-start.x,e.clientY-start.y,start.width,start.dragging);start.dragging=peek.dragging;if(peek.dragging){suppressClick.current=true;setOffset(peek.offset)}}
 function end(e:PointerEvent<HTMLButtonElement>){const start=gesture.current;if(start?.id!==e.pointerId)return;gesture.current=null;setOffset({x:0,y:0});if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!playable&&!start.dragging){blockedFeedback();suppressClick.current=true}}
 const arrowKeys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'];
 function keyDown(e:KeyboardEvent<HTMLButtonElement>){if(inspectable&&arrowKeys.includes(e.key)){e.preventDefault();if(!e.repeat)onInspect(t.key);tileWidth.current=e.currentTarget.offsetWidth;const distance=tileWidth.current*1.15;setOffset({x:e.key==='ArrowLeft'?-distance:e.key==='ArrowRight'?distance:0,y:e.key==='ArrowUp'?-distance:e.key==='ArrowDown'?distance:0})}}
 useEffect(()=>{onPeek(t.key,{x:offset.x/tileWidth.current,y:offset.y/tileWidth.current})},[offset.x,offset.y]);
 const displaced=offset.x!==0||offset.y!==0;
 return <button ref={button} aria-label={visible?`Pair ${t.pair} ${t.half==='a'?'left':'right'} half${rack?' in work area':playable?', playable':inspectable?', drag to inspect only':', covered'}`:'Face-down tile, covered'} disabled={rack} className={`tile ${playable?'free':'blocked'} ${inspectable?'inspectable':''} ${displaced?'peeking':''} ${hinted?'hinted':''} ${visible?'':'face-down'}`} style={rack?{}:{left:`${t.x*15.5+2+t.z*.7}%`,top:`${t.y*23+5-t.z*1.7}%`,zIndex:displaced?80:t.z*10+1,transform:displaced?`translate(${offset.x}px, ${offset.y}px)`:undefined}} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={()=>{gesture.current=null;setOffset({x:0,y:0})}} onKeyDown={keyDown} onKeyUp={e=>{if(arrowKeys.includes(e.key))setOffset({x:0,y:0})}} onBlur={()=>setOffset({x:0,y:0})} onClick={e=>{if(suppressClick.current&&e.detail!==0){suppressClick.current=false;e.preventDefault();return}if(e.detail===0)onInspect(t.key);if(playable)onSelect();else blockedFeedback()}}><span className={`tile-flipper ${visible?'':'flipped'}`} aria-hidden="true"><span className="tile-front"><img draggable={false} src={manifest[t.pair-1][t.half]} alt=""/></span><span className="tile-back"><span className="back-emblem">◇</span></span></span></button>
}
