import {free,select,continueGame,type Game} from './engine';
type Tool={name:string,title:string,description:string,inputSchema:object,annotations:{readOnlyHint:boolean,untrustedContentHint:boolean},execute:(input:unknown)=>unknown};
type Context={registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>};
export function registerGameTools(read:()=>{g:Game,blocked:boolean},write:(g:Game)=>void,context:Context|undefined=(typeof document==='undefined'?undefined:(document as Document&{modelContext?:Context}).modelContext)){
 if(!context)return;const life=new AbortController();
 const summary=()=>{const {g,blocked}=read();return {level:g.level,status:g.status,completed:g.completed,reveal:g.reveal,blocked,rack:g.rack.map(t=>({pair:t.pair,half:t.half})),playable:g.board.filter(t=>free(t,g.board)).map(t=>({key:t.key,pair:t.pair,half:t.half}))}};
 const tools:Tool[]=[{name:'read_matching_game',title:'Read matching game',description:'Read playable tiles, work area and current reveal.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:summary},{name:'select_matching_tile',title:'Select tile',description:'Move one free tile into the work area. A match opens its reveal.',inputSchema:{type:'object',properties:{key:{type:'integer'}},required:['key'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const key=(input as {key?:unknown})?.key;const {g,blocked}=read();if(!Number.isInteger(key)||blocked||g.reveal||g.status!=='playing')throw Error('Tile selection unavailable');const next=select(g,key as number);if(next===g||next.board.length===g.board.length)throw Error('Tile is blocked or rack is full');write(next);return summary()}},{name:'continue_match_reveal',title:'Continue match reveal',description:'Close the current match reveal and resume play, or show completion.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){const {g,blocked}=read();if(!g.reveal||blocked)throw Error('No match reveal to continue');write(continueGame(g));return summary()}}];
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}
 return ()=>life.abort();
}
